%YAML 1.2
---
projects:
  - eclipse/microprofile-samples
  - eclipse/microprofile-conference
  - eclipse/microprofile
  - eclipse/microprofile-config
  - eclipse/microprofile-evolution-process
  - eclipse/microprofile-fault-tolerance
  - eclipse/microprofile-sandbox
  - eclipse/microprofile-health
  - eclipse/microprofile-jwt-auth
  - eclipse/microprofile-bom
  - eclipse/microprofile-metrics
  - eclipse/microprofile-open-api
  - eclipse/microprofile-rest-client
  - eclipse/microprofile-opentracing
  - eclipse/microprofile-reactive-streams
  - eclipse/microprofile-reactive-messaging
  - eclipse/microprofile-lra
  - eclipse/microprofile-service-mesh
  - eclipse/microprofile-service-mesh-service-a
  - eclipse/microprofile-service-mesh-service-b
  - eclipse/microprofile-concurrency
  - eclipse/microprofile-starter
  - eclipse/microprofile-parent
  
